apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        dineshgitbot/golang-test-http: true
        jenkinsxgitorg/aspnet-app-test: true
        jenkinsxgitorg/golang-http-2: true
        jenkinsxgitorg/golang-http-test: true
        jenkinsxgitorg/jx3-golang-demo3: true
        jenkinsxgitorg/jx3-kube-setup: true
        jenkinsxgitorg/ps-jx-java-quickstart: true
        jenkinsxgitorg/spring-boot-app: true
        jenkinsxgitorg/spring-boot-http-gradle: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: true
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        dineshgitbot/golang-test-http: merge
        jenkinsxgitorg/aspnet-app-test: merge
        jenkinsxgitorg/golang-http-2: merge
        jenkinsxgitorg/golang-http-test: merge
        jenkinsxgitorg/jx3-golang-demo3: merge
        jenkinsxgitorg/jx3-kube-setup: merge
        jenkinsxgitorg/ps-jx-java-quickstart: merge
        jenkinsxgitorg/spring-boot-app: merge
        jenkinsxgitorg/spring-boot-http-gradle: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - jenkinsxgitorg/jx3-kube-setup
        - dineshgitbot/golang-test-http
        - jenkinsxgitorg/aspnet-app-test
        - jenkinsxgitorg/golang-http-2
        - jenkinsxgitorg/golang-http-test
        - jenkinsxgitorg/jx3-golang-demo3
        - jenkinsxgitorg/ps-jx-java-quickstart
        - jenkinsxgitorg/spring-boot-app
        - jenkinsxgitorg/spring-boot-http-gradle
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - jenkinsxgitorg/jx3-kube-setup
        - dineshgitbot/golang-test-http
        - jenkinsxgitorg/aspnet-app-test
        - jenkinsxgitorg/golang-http-2
        - jenkinsxgitorg/golang-http-test
        - jenkinsxgitorg/jx3-golang-demo3
        - jenkinsxgitorg/ps-jx-java-quickstart
        - jenkinsxgitorg/spring-boot-app
        - jenkinsxgitorg/spring-boot-http-gradle
      target_url: http://lighthouse-jx.dineshpatil.net/merge/status
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
